services:
  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  mssql_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "2026"
    ports:
      - "1433:1433"            

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn main:app --host 127.0.0.1
    ports:
      - "8000:8000"
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres_db
      - redis
      - mssql_db

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - postgres_db

  scheduler:
    build: .
    command: python scheduler_script.py
    depends_on:
      - mssql_db
      - postgres_db

volumes:
  pgdata: